parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true



  oliverde8\ComfyBundle\Storage\StorageInterface:
    class: oliverde8\ComfyBundle\Storage\DoctrineEntityStorage

  oliverde8\ComfyBundle\Manager\ConfigManagerInterface:
    class: oliverde8\ComfyBundle\Manager\ConfigManager

  oliverde8\ComfyBundle\Manager\ConfigDisplayManager:
    class: oliverde8\ComfyBundle\Manager\ConfigDisplayManager

  oliverde8\ComfyBundle\Resolver\VisibleConfigsResolver:
      class: oliverde8\ComfyBundle\Resolver\VisibleConfigsResolver


  oliverde8\ComfyBundle\Command\:
    resource: "../../Command/*"

  oliverde8\ComfyBundle\Form\:
    resource: "../../Form/*"

  oliverde8\ComfyBundle\Security\:
    resource: "../../Security/*"
